#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May  7 15:30:48 2020

@author: marcpozzo
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import argparse
#import utiles
import cv2
from os import chdir
import numpy as np
chdir("/mnt/VegaSlowDataDisk/c3po_interface_mark/find_dominant_colors/python-kmeans-dominant-colors/color_kmeans.py")


import matplotlib.pyplot as plt
import numpy as np


Blue=np.array([255,0,0])
Red=np.array([0,255,0])
Green=np.array([0,0,255])


Blue=[255,0,0]
Red=[0,255,0]
Green=[0,0,255]

colors=np.array([Blue,Red,Green])

image_path="/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_0/image_2019-04-30_17-41-18.jpg"
img=cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

terre=img[650:]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))

"""
np.mean((terre[:,:,0]))
Out[305]: 243.62637867647058
np.mean((terre[:,:,1]))
Out[306]: 215.20873579545454
np.mean((terre[:,:,2]))
Out[307]: 175.6268089906417



std
image grande malgré tout écart type relativement peu élevé

32.660269703168744

14.602549734354772
16.7942384289316
19.28871354224846
"""





#Photo 2


image_path="/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_0/image_2019-05-17_20-32-47.jpg"
img=cv2.imread(image_path)
img=cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

terre=img[650:]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))


"""
dossier 0 terre
Ici c'est plutôt le soir
118.04643973214286
107.70310267857143
102.97391741071428
"""

#Complètement nuit
#/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_3/image_2019-05-31_04-36-55.jpg



image_path="/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_0/image_2019-05-17_18-32-39.jpg"
img=cv2.imread(image_path)
img=cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

terre=img[650:]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))


"""
jour
218.0940736607143
200.68716517857143
189.34069196428572


std
20.274613718661477

16.24221243791937
16.707382230069577
16.453991603855787


"""




image_path="/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_0/image_2019-05-17_18-32-39.jpg"
img=cv2.imread(image_path)
img=cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

terre=img[80:150,700:750]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))


"""
arbre
89.24142857142857
119.77828571428572
115.01914285714285
"""


#fichier 4





image_path="/mnt/VegaSlowDataDisk/c3po/Images_aquises/DonneesPI/timeLapsePhotos_Pi1_4/image_2019-06-16_10-20-55.jpg"
img=cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

terre=img[550:,:400]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))

"""
#Ecart type à l'air très grand entre les images
terre de devant jour dossier 4
print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))



31.259457412512734
31.33082537493266
29.040948591960472
std=33.058275020683
"""

terre=img[275:300,600:1000]
plt.imshow(terre)

print(np.mean((terre[:,:,0])))
print(np.mean((terre[:,:,1])))
print(np.mean((terre[:,:,2])))

"""
terre très claire en haut de l'image
210.9603
198.7751
190.0305
ça ressemble beaucoup à une autre photo du dossier 0!!!
"""